### ISSUE TITLE
download function glitch?

### ISSUE THREAD

**Issue by ghostguy** [Colossal1/plugin.video.xxx-o-dus#17]
there seems to be a glitch in xxx-o-dus on xnxx tube
when i highlight a video and get the D/L option
it spawns a window  about the download but all the time fields are 00:00
so when it is clicked it downloads about 145b an says it's done
i've tried other tubes and those worked
Thanks! for the great job you're doing

Bob

**Comment by Colossal1** [comment]
This is due to the site not allowing download of the files.
