### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by ohmichael** [Colossal1/plugin.video.xxx-o-dus#18]
Some scrapers present errors when playing

**Comment by Colossal1** [comment]
Please upload a log to show the errors.

**Comment by zmxncb** [comment]
One example is streamingporn.

A fix would be to change linkfinder.py to have this:

if 'streamingporn.xyz' in url:
            c = client.request(url)
            r = dom_parser2.parse_dom(c, 'a', {'class': 'external'}, req=['href'])
            r = [client.request(i, output="geturl") for i in (x.attrs['href'] for x in r if not "<img" in x.content)]
            r = [i for i in r if urlresolver.HostedMediaFile(i).valid_url()]
            url = multi(r)

I'm not a Python dev so there might be a better way to solve this.

**Comment by ohmichael** [comment]
it extracts but links get errors when playing

**Comment by ohmichael** [comment]
Just fix link extracter & urlresolver for streamingporn

**Comment by Colossal1** [comment]
Fixed for next update

**Comment by ohmichael** [comment]
Ok ty cant wait you rule sry i cant show log i did once and it confused me & sry i pissed you off
