### ISSUE TITLE
Movies

### ISSUE THREAD

**Issue by rockinrichy** [Colossal1/plugin.video.xxx-o-dus#2]
Hi again. Thanks for including the dedicated movie section.

Is there any chance you can add the scrapers that were present in version 2.xx of the addon for movies? They seemed to give much more access to European movies and new releases, particularly the French stuff such as Marc Dorcel.
Cheers
R

**Comment by echocoderxbmc** [comment]
I am not sure what was present in the version 2. Can you let me know which sites these were please?
