### ISSUE TITLE
Length feature-might work

### ISSUE THREAD

**Issue by ohmichael** [Colossal1/plugin.video.xxx-o-dus#22]
Can you add sort by option or length below or above 20 minutes also can you show length of clip/film next to video so i know its short or long & streamingporn only opened up 4 me cuz i had it in super fav. -in xxxodus it wont open & in both videos dont stream-log coming next to help

**Comment by ohmichael** [comment]
https://pastebin.com/raw/5qM47k3C - uwc spankbang malfunction also in log expires in 24 hrs

**Comment by ohmichael** [comment]
last guy i showed log to went off cuz i i have over 800 repos & addons not the point but told you my reasoning i hate logs.- tknorris - i try to respect but i hate rudeness thats all goodluck.

**Comment by ohmichael** [comment]
Still no updates

**Comment by Colossal1** [comment]
Im a little confused what you are asking here.

I cannot guess the length of videos. If the site has a duration I add them, if not I cannot add them.

**Comment by ohmichael** [comment]
Ok th
