### ISSUE TITLE
Site Nxgx not loading links

### ISSUE THREAD

**Issue by a7mag3ddon** [Colossal1/plugin.video.xxx-o-dus#24]
Site Nxgx does not load any playable links.

Tested site on desktop using same connection and also fails... Until you turn off the adblocker on the browser, then all links play without problems.

Site seems to be checking for either a pop-up blocker OR that an extra window has opened before playing the video.

Is this something that can be fixed in xxx-O-dus ?

**Comment by Colossal1** [comment]
Fixed
