### ISSUE TITLE
XXX-O-DUS latest version -scrapper error

### ISSUE THREAD

**Issue by gh0stid** [Colossal1/plugin.video.xxx-o-dus#25]
Hello,

first of all thank you for the good work, unfortunately  it seem to have a problem, all of the tube give error.

i went to see into the logs and apparentely it has something to do with ACCESS DENIED for the scrapper ?

ive attached a log files.

Thank you !
[error.log.txt](https://github.com/Colossal1/plugin.video.xxx-o-dus/files/1415907/error.log.txt)

**Comment by Colossal1** [comment]
Your log reports the following:

`Adguard DNS blocked this page because you use &quot;Family protection&quot; mode.`

I would suggest disabling any protection and retrying.
