### ISSUE TITLE
live cams,chaturbate

### ISSUE THREAD

**Issue by viper7575** [Colossal1/plugin.video.xxx-o-dus#28]
hi i have recently just updated to kodi 17.5 and when i try and view get failed to get any playable link on all ?

**Comment by StockportJambo** [comment]
This happens on 17.4 too. Chaturbate has broken.

**Comment by falu84** [comment]
I'm having the same issue what should I do

**Comment by Buddha2400** [comment]
The same problem here and when I was able to view a cam there was no sound even though I could go on to chaturbate from my desktop. View the same cam and get sound.

**Comment by wingnut02** [comment]
Same problem. "Unable to find playable link" message on just about every performer I choose.

**Comment by Colossal1** [comment]
Fixed
