### ISSUE TITLE
Live channels

### ISSUE THREAD

**Issue by REPendragon** [Colossal1/plugin.video.xxx-o-dus#3]
I haven't been able to get anything from the live channels on the xxx-o-dus addon for a few days. Did they get removed or is an issue getting fixed??  Thanks

**Comment by Colossal1** [comment]
XXXODUS 2 did not come with any live channels built into it.

It is very hard to find any reliable live XXX channels but if any stable ones come about they will be added.

I am worried however that you are not using the latest version of XXXODUS so can you please confirm the version you are using.

Thank you.
