### ISSUE TITLE
Scenes Streamingporn returning a scraper error

### ISSUE THREAD

**Issue by nmanx62** [Colossal1/plugin.video.xxx-o-dus#31]
Hi. I have attached the error returned when the Scenes / Streamingporn link is clicked, hope you are able to resolve.
[Streamingporn scraping error.txt](https://github.com/Colossal1/plugin.video.xxx-o-dus/files/1451645/Streamingporn.scraping.error.txt)

**Comment by ohmichael** [comment]
Please fix this also

**Comment by Colossal1** [comment]
Fixed
