### ISSUE TITLE
Scenes Virtualpornstars returning a scraper error

### ISSUE THREAD

**Issue by nmanx62** [Colossal1/plugin.video.xxx-o-dus#32]
Hi, I've found that Scenes - Virtualpornstars is also returning a scraper error, pertinent log entry attached.
[Virtualpornstars scraping error.txt](https://github.com/Colossal1/plugin.video.xxx-o-dus/files/1451673/Virtualpornstars.scraping.error.txt)

**Comment by Colossal1** [comment]
Fixed
