### ISSUE TITLE
XXX-O-DUS  crashes if try to download videos

### ISSUE THREAD

**Issue by aaroetex** [Colossal1/plugin.video.xxx-o-dus#4]
crashes only if try download...work fine to view.
using WIN10 64 bit
 Kodi 17.3
right click context menu to download and errors out. have to kill Kodi.

16:36:46.143 T:2732 WARNING: CPythonInvoker(19, C:\Users\A\AppData\Roaming\Kodi\addons\plugin.video.xxx-o-dus\default.py): the python script "C:\Users\A\AppData\Roaming\Kodi\addons\plugin.video.xxx-o-dus\default.py" has left several classes in memory that we couldn't clean up. The classes include: class XBMCAddon::xbmcaddon::Addon
16:36:50.625 T:4172  NOTICE: URLResolver: Initializing URLResolver version: 4.0.02

Thanks is advance.

**Comment by Colossal1** [comment]
That issue will be fixed tonight and released with an update.

Thanks for letting me know.
