### ISSUE TITLE
You Porn

### ISSUE THREAD

**Issue by babingez** [Colossal1/plugin.video.xxx-o-dus#5]
Hi again, Just reporting Youporn on XXX-O-DUS is reporting back "fatal error". Thank you as always :-)

**Comment by Colossal1** [comment]
Can you please provide a log.

**Comment by Colossal1** [comment]
Fixed in 3.00.030

**Comment by babingez** [comment]
Brilliant work as always. Sorry I didnt get back before you sorted the problem and could I be silly and ask -  the log was it a copy of the main event log you had wanted. Sorry but I am a bit dim :-) 
Just a request, is there any chance of getting Javtasty back? 
Thank you again for the very best addon.
