### ISSUE TITLE
OSMC - Can't Remove Single Voice on "Search History"....

### ISSUE THREAD

**Issue by DjDiabolik** [Colossal1/plugin.video.xxx-o-dus#7]
I'm actually have xxx-o-dus latest version installed on latest version of OSMC....
Apparently all works whitout any problems but i have notified a little troubles (try to explain whit my bad english):
On "Search History" by a "Context Menu" it's possibly to remove one single search terms...... i have tryed to remove someone on my kodi setup and i see the "spin" on screen of tv, after about 10 seconds i obtain a notification on screen says somethigs like voices it's deleted but i go back and return on search history and i see nothings appends. The search terms removed previously it's not be deleted....... it's ever present on the list.

Ah... i can add an info... if i use the "feature" for clear all history search this is works. Only the single voice it's can not be deleted.....

Thanks in advance for this little fix... and i hope i do a correct mode to send a bug 👍

**Comment by Colossal1** [comment]
Thank you for raising the issue.

Could you please upload a debug log for me to see what is going on.

http://koditips.com/kodi-how-to-check-log/

**Comment by DjDiabolik** [comment]
mmmmmmmm... ok....... i need to activate the main "debug" log of kodi of this addons have a own debug it's settings ?

**Comment by Colossal1** [comment]
Main debug will be fine. Thanks

**Comment by DjDiabolik** [comment]
Oh ok.... as soon as I post all.... i try to activate debug.. restart osmc.... and try to delete a single voice and after that see what's append on debug log :)

**Comment by DjDiabolik** [comment]
[Log_Debug_Remove_Single_terms.txt](https://github.com/Colossal1/plugin.video.xxx-o-dus/files/1301268/Log_Debug_Remove_Single_terms.txt)

Ok Ok... i have some minutes to post debug log......... i have to do this:
1) I have created a new search terms called "TEST"
2) Wait complete search
3) Back to Home of OSMC and enabled DEBUG on LOG
4) Back on Search History and i have tryed to remove single text whit option on context menu.

After about 10 seconds i see the notification on upper right screen......... back on "Home" of XXX-O-DUS.
After this i re-enter to search history and the "TEST" voice it's not be deleted.. it's still here ever :)

I have upload the LOG immediatelly after i have enabled the DEBUG... you can see it at first line...
I hope this is usefull.......

**Comment by Colossal1** [comment]
Ok thanks, I will look at it in the next day or two.

**Comment by DjDiabolik** [comment]
OMG!! Great :) Thanks @Colossal1 Thanks again :)
